### ISSUE TITLE
Plugin prepends blank effect layer

### ISSUE THREAD

**Issue by alexwidua** [alexwidua/figma-beautiful-shadows#2]
The plugin prepends a blank effect layer (offset: 0) which has no impact on the actual shadow effect.

References [this comment](https://www.figma.com/community/plugin/1068595505353552645/Beautiful-Shadows?comment=1080846743162225793) on Figma community.

**Comment by joebez** [comment]
I'm creating a SwiftUI ViewModifier based on your code, and I noticed this same issue, caused by the fact that the normalized easing functions are essentially 0 (or 1) at the extremes.

What I did to "solve" this is to normalize the shadow array index within a range that's two steps larger than, instead of equal to, the array count. So rather than `normalize(i, 0, numShadows)`, I used `normalize(i+1, 0, numShadows+2`. This makes it so the normalized values at `i = 0` and `i = numShadows - 1` are a bit farther away from 0 (or 1).

To my eye it makes a _little_ bit of difference, but maybe I'm just convincing myself of that. :-)

**Comment by alexwidua** [comment]
Hi @joebez,
thank you for surfacing this issue again :-) I've deployed a fix that removes the transparent drop-shadow (I'm simply filtering out all empty shadows).

/a

**Comment by joebez** [comment]
Hi @alexwidua. You're welcome. Always happy to dig up old issues. 😂

I'm going give this some more thought as I work on my SwiftUI version. The "problem" is that there's not just one "empty" shadow, there's actually two, because the first shadow has a (rounded to) zero offset and a (rounded to) zero blur radius, and the last shadow has a shadow color with (rounded to) 0% opacity. If you set `numShadows` to 6, you actually get back 4 shadows that will affect the appearance. E.g.,

```
box-shadow:
  0px 0px 0px 0px rgba(0, 0, 0, 0.12),
  0px 8px 18px 0px rgba(0, 0, 0, 0.12),
  0px 33px 33px 0px rgba(0, 0, 0, 0.10),
  0px 74px 45px 0px rgba(0, 0, 0, 0.06),
  0px 132px 53px 0px rgba(0, 0, 0, 0.02),
  0px 206px 58px 0px rgba(0, 0, 0, 0.00);
```

That's just the way the easing function math works, but I'd like to find a way to get `n` usable shadows out of the algorithm instead of `n-2`.
